CC=gcc
CFLAGS=-Wall -Werror -Werror -pedantic -std=c11

all: clean amount_from_1_to_n surface_area sum_of_even checking_for_simplicity around min_max emergency clocks box

amount_from_1_to_n:
	rm -rf amount_from_1_to_n
	$(CC) $(CFLAGS) 1.amount_from_1_to_n.c -o amount_from_1_to_n
surface_area:
	rm -rf surface_area
	$(CC) $(CFLAGS) 2.surface_area.c -o surface_area
sum_of_even:
	rm -rf sum_of_even
	$(CC) $(CFLAGS) 3.sum_of_even.c -o sum_of_even
checking_for_simplicity:
	rm -rf checking_for_simplicity
	$(CC) $(CFLAGS) 4.checking_for_simplicity.c -o checking_for_simplicity
around:
	rm -rf around
	$(CC) $(CFLAGS) 5.around.c -o around
min_max:
	rm -rf min_max
	$(CC) $(CFLAGS) 6.min_max.c -o min_max
emergency:
	rm -rf emergency
	$(CC) $(CFLAGS) 7.emergency.c -o emergency
clocks:
	rm -rf clocks
	$(CC) $(CFLAGS) 8.clocks.c -o clocks
box:
	rm -rf box
	$(CC) $(CFLAGS) 9.box.c -o box

clean:
	rm -rf amount_from_1_to_n surface_area sum_of_even checking_for_simplicity around min_data min_max emergency clocks box *.o *.a *.out *.dSYM