CC=gcc
CFLAGS=-Wall -Werror -Werror -pedantic -std=c11

all: clean cmp_elements summs_k gistogramma summ func difference_r brainwash number_systems letters_of_the_alphabet

cmp_elements:
	rm -rf cmp_elements
	$(CC) $(CFLAGS) 1.cmp_elements.c -o cmp_elements
summs_k:
	rm -rf summs_k
	$(CC) $(CFLAGS) 2.summs_k.c -o summs_k
gistogramma:
	rm -rf gistogramma
	$(CC) $(CFLAGS) 3.gistogramma.c -o gistogramma
summ:
	rm -rf summ
	$(CC) $(CFLAGS) 4.summ.c -o summ
func:
	rm -rf func
	$(CC) $(CFLAGS) 5.func.c -o func
difference_r:
	rm -rf difference_r
	$(CC) $(CFLAGS) 6.difference_r.c -o difference_r
brainwash:
	rm -rf brainwash
	$(CC) $(CFLAGS) 7.brainwash.c -o brainwash
number_systems:
	rm -rf number_systems
	$(CC) $(CFLAGS) 8.number_systems.c -o number_systems
letters_of_the_alphabet:
	rm -rf letters_of_the_alphabet
	$(CC) $(CFLAGS) 9.letters_of_the_alphabet.c -o letters_of_the_alphabet
	

clean:
	rm -rf cmp_elements summs_k gistogramma summ func min_nunber_systems difference_r brainwash number_systems letters_of_the_alphabet *.o *.a *.out *.dSYM